const states = { explorando:{label:'Explorando',icon:'✦',description:'Mochi busca algo nuevo que descubrir.',color:'#f5c96a',target:[1,10],energy:-1,mood:1,curiosity:3}, hambriento:{label:'Hambriento',icon:'◒',description:'Sigue el aroma hasta su cuenco favorito.',color:'#e9a06d',target:[5,1],energy:-2,mood:-1,curiosity:0}, feliz:{label:'Feliz',icon:'☀',description:'Da una vuelta celebrando que todo va bien.',color:'#a9d9bf',target:[2,10],energy:-1,mood:3,curiosity:1}, cansado:{label:'Cansado',icon:'☾',description:'Busca un rincón tranquilo para recuperar energía.',color:'#c1b6e4',target:[5,10],energy:4,mood:0,curiosity:-1}, curioso:{label:'Curioso',icon:'⊙',description:'Inspecciona la esquina más misteriosa del jardín.',color:'#94c7d3',target:[1,6],energy:-2,mood:1,curiosity:4}, aburrido:{label:'Aburrido',icon:'—',description:'Se mueve sin rumbo buscando algo de diversión.',color:'#edb5a3',target:[3,6],energy:-1,mood:-2,curiosity:2}, dormido:{label:'Dormido',icon:'zZ',description:'Zzz... una siesta corta para volver a brillar.',color:'#b5c7d9',target:[5,6],energy:7,mood:1,curiosity:-3} };
const stateKeys = Object.keys(states), cols = 12, rows = 7, obstacles = new Set(['0-3','0-4','1-3','2-3','3-3','4-8','4-9','5-8','6-2','6-3','2-7','3-7']);
let position = [3,1], currentState = 'explorando', goal = states[currentState].target, path = [], pathIndex = 0, autoTimer = 6, manualPause = 0, vitals = {energy:78,mood:84,curiosity:66};
const map = document.querySelector('#map'), controls = document.querySelector('#state-controls'), activityLog = document.querySelector('#activity-log');
function key(cell) { return `${cell[0]}-${cell[1]}`; }
function neighbors([row,col]) { return [[row-1,col],[row+1,col],[row,col-1],[row,col+1]].filter(([r,c]) => r >= 0 && r < rows && c >= 0 && c < cols && !obstacles.has(key([r,c]))); }
function heuristic(a,b) { return Math.abs(a[0]-b[0]) + Math.abs(a[1]-b[1]); }
function findPath(start,end) { const open = [{cell:start,score:0}], cameFrom = new Map(), cost = new Map([[key(start),0]]); while (open.length) { open.sort((a,b) => a.score-b.score); const current = open.shift().cell; if (key(current) === key(end)) { const result = [current]; let cursor = key(current); while (cameFrom.has(cursor)) { const previous = cameFrom.get(cursor); result.unshift(previous); cursor = key(previous); } return result; } neighbors(current).forEach(next => { const newCost = cost.get(key(current)) + 1; if (!cost.has(key(next)) || newCost < cost.get(key(next))) { cost.set(key(next),newCost); cameFrom.set(key(next),current); open.push({cell:next,score:newCost+heuristic(next,end)}); } }); } return [start]; }
function renderMap() { map.innerHTML = ''; for (let row=0; row<rows; row+=1) for (let col=0; col<cols; col+=1) { const tile=document.createElement('div'), cell=[row,col]; tile.className='tile'; tile.setAttribute('role','gridcell'); if (obstacles.has(key(cell))) tile.classList.add('obstacle'); if (path.some(item => key(item)===key(cell)) && key(cell)!==key(position)) tile.classList.add('path'); if (key(cell)===key(goal)) tile.classList.add('goal'); if (key(cell)===key(position)) tile.classList.add('pet'); map.appendChild(tile); } }
function renderControls() { controls.innerHTML = stateKeys.map((state,index) => `<button class="state-button ${state===currentState?'selected':''}" data-state="${state}" type="button"><span class="state-icon">${states[state].icon}</span><b>${states[state].label}</b><small>ir a ${String(index+1).padStart(2,'0')}</small></button>`).join(''); controls.querySelectorAll('button').forEach(button => button.addEventListener('click', () => setState(button.dataset.state,true))); }
function addLog(message,tag='A* PATH') { const time=new Date().toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'}), item=document.createElement('div'); item.className='log-item'; item.innerHTML=`<span class="log-time">${time}</span><strong>${message}</strong><span class="log-tag">${tag}</span>`; activityLog.prepend(item); while (activityLog.children.length>4) activityLog.lastElementChild.remove(); }
function updateUI() { const data=states[currentState]; document.querySelector('#state-name').textContent=data.label; document.querySelector('#state-description').textContent=data.description; document.querySelector('#state-number').textContent=String(stateKeys.indexOf(currentState)+1).padStart(2,'0'); document.querySelector('#room-state').textContent=String(stateKeys.indexOf(currentState)+1).padStart(2,'0'); const face=document.querySelector('#mood-face'); face.style.background=data.color; face.dataset.state=currentState; document.querySelector('#speech-bubble').textContent=data.label === 'Dormido' ? 'Zzz...' : data.label === 'Hambriento' ? 'ñam ñam' : data.label === 'Feliz' ? '¡yupi!' : data.label === 'Cansado' ? 'qué sueño...' : data.label === 'Curioso' ? '¿eh?' : data.label === 'Aburrido' ? 'hm...' : '¡Hola!'; document.querySelector('#route-label').textContent=`ruta hacia ${data.label.toLowerCase()}`; document.querySelector('#step-counter').textContent=`paso ${String(Math.min(pathIndex+1,path.length)).padStart(2,'0')} / ${String(path.length).padStart(2,'0')}`; document.querySelector('#countdown').textContent=`${String(autoTimer).padStart(2,'0')}s`; ['energy','mood','curiosity'].forEach(name => { vitals[name]=Math.max(0,Math.min(100,vitals[name])); document.querySelector(`#${name}-value`).textContent=`${vitals[name]}%`; document.querySelector(`#${name}-meter`).style.width=`${vitals[name]}%`; }); }
function setState(nextState,isManual=false) { currentState=nextState; goal=states[nextState].target; path=findPath(position,goal); pathIndex=0; autoTimer=6; if (isManual) { manualPause=10; document.querySelector('#system-status').textContent='control manual activo'; addLog(`Mochi cambió a ${states[nextState].label.toLowerCase()}`,'TÚ ELEGISTE'); } else addLog(`Mochi ahora está ${states[nextState].label.toLowerCase()}`,'AUTÓNOMO'); renderControls(); renderMap(); updateUI(); }
function move() { if (pathIndex<path.length-1) { pathIndex+=1; position=path[pathIndex]; vitals.energy+=states[currentState].energy; vitals.mood+=states[currentState].mood/3; vitals.curiosity+=states[currentState].curiosity/3; renderMap(); updateUI(); } }
function autonomousDecision() { setState(stateKeys[Math.floor(Math.random()*stateKeys.length)]); }
function pulse() { autoTimer-=1; if (manualPause>0) manualPause-=1; if (manualPause===0) document.querySelector('#system-status').textContent='sistema autónomo activo'; if (autoTimer<=0) { autoTimer=6; autonomousDecision(); } move(); updateUI(); }
document.querySelector('#clear-log').addEventListener('click', () => { activityLog.innerHTML='<div class="log-item empty">El registro está limpio. Mochi sigue explorando.</div>'; });
setState('explorando'); addLog('Mochi despertó en el jardín','INICIO'); setInterval(pulse,1000);